local weapons = {}

weapons.weapon_models = {
    [`w_ar_goldak`] = true,
    [`w_ar_akm`] = true,
    [`w_ar_AK200`] = true,
    [`w_ar_m16a1`] = true,
    [`w_ar_MXM`] = true,
    [`w_ar_m4a1`] = true,
    [`w_ar_mosin`] = true,
    [`w_ar_mxc`] = true,
    [`w_ar_SPAR16`] = true,
    [`w_ar_MK1EMR`] = true,
    [`w_sr_svd`] = true,
    [`w_ar_SINGULARITYPHANTOM`] = true,
    [`w_ar_gura`] = true,
    [`w_ar_ANIMEM16`] = true,
    [`w_sb_DIAMONDMP5`] = true,
    [`w_sr_gungnir`] = true,
    [`w_ar_blastxphantom`] = true,
    [`w_ar_grau`] = true,
    [`w_ar_rgxvandal`] = true,
    [`w_ar_phantom`] = true,
    [`w_sr_l96`] = true,
    [`w_ar_primevandal`] = true,
    [`w_sr_locus`] = true,
    [`w_sr_blastxspectre`] = true,
    [`w_ar_hk`] = true,
    [`w_mg_odin`] = true,
    [`w_pi_glock17`] = true,
    [`w_sr_hyperbeast`] = true,
    [`w_sg_usas`] = true,
    [`w_ar_sigmpx`] = true,
    [`w_me_blade_01`] = true,
    [`w_sg_fortnite`] = true,
    [`w_pi_nikeglock`] = true,
    [`w_sb_fademp5`] = true,
    [`w_ar_m16a2`] = true,
    [`w_ar_m4a1`] = true,
    [`w_pi_deagle`] = true,
    [`w_sg_sawnoff`] = true,
    [`w_mg_m249`] = true,
    [`w_sr_ax502`] = true,
}

return weapons