
local cfg = {}


cfg.groups = {
	["dev"] = {
        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",
		"dev.givemoney",
		"dev.tp2coords",
	    "dev.getcoords",
		"cardev.menu",
		"chat.announce",
		"admin.addcar",
		"admin.spawnGun",
        "admin.menu",
        "admin.warn",
		"admin.vehmenu",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
		
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",

		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
	},
	["leaddev"] = {
		"dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",
		"dev.givemoney",
		"dev.tp2coords",
	    "dev.getcoords",
		"cardev.menu",
		"chat.announce",
		
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
		"chat.announce",
		"cardev.menu",
	},
	["founder"] = {
		
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
		"chat.announce",
		"cardev.menu",
	},
	["operationsmanager"] = {
        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",
		"dev.givemoney",
		"dev.tp2coords",
	    "dev.getcoords",
		"admin.special",
		"cardev.menu",
		"chat.announce",


		"admin.addcar",
		"admin.spawnGun",
        "admin.menu",
        "admin.warn",
		"admin.vehmenu",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
		
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",

		"group.add.vip",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
	},
	["staffmanager"] = {
		"dev.menu",
        "dev.spawncar",
        "dev.deletecar",
        "dev.fixcar",
		"dev.tp2coords",
	    "dev.getcoords",
		"admin.vehmenu",
		"admin.special",
		
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
		"admin.addcar",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"cardev.menu",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",
		"group.add.vip",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
	},
	["commanager"] = {
		
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.addcar",
		"admin.freeze",
		"admin.getgroups",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.givemoney",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",

        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
	  },
	["headadmin"] = {
		
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",
		"admin.donoAddGroups",

		
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
  },
  ["senioradmin"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
		"admin.whitelisted",
		"admin.tickets",
  },
  ["administrator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.noclip",

		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
  },
  ["srmoderator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.screenshot",
		"admin.spectate",

		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
    },
  ["moderator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.screenshot",
		"admin.spectate",

		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
  },
  ["supportteam"] = {
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.kick",
		"admin.spectate",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.ban",
		
  },
  ["trialstaff"] = {
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.kick",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
  },
  ["cardev"] = {
	"cardev.menu",
},
     -- ["god"] = {
    -- "admin.god" -- reset survivals/health periodically
  -- },

  -- the group user is auto added to all logged players
  ["user"] = {
    "player.phone",
    "player.calladmin",
	"player.fix_haircut",
	"player.check",
	--"mugger.mug",
	"player.skip_coma",
	"player.store_money",
	"player.check",
	"player.loot",
	"player.player_menu",
	"player.userlist",
	"user.paycheck"
  },

  -- [Donator Ranks]

  ["bronze"] = {},
  ["silver"] = {},
  ["gold"] = {},
  ["platinum"] = {},

    -- [Claimed Reward Ranks]

	["10hrs"] = {},
	["25hrs"] = {},
	["50hrs"] = {},

  -- [Pov List]

  ["pov"] = {
	"pov.list"
  },
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "founder",
	"admin",
  }
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  
}

return cfg